- name: Download kubeconfig
  ansible.builtin.uri:
    url: https://your.form.based.auth.example.com/index.php
    method: POST
    body_format: form-urlencoded
    dest: "{{ zip_path }}"
    headers: 
        Authorization: '{{ IC_IAM_TOKEN }}'
        X-Auth-Refresh-Token: '{{ IC_IAM_REFRESH_TOKEN }}'
        X-Auth-Resource-Group: '42ee88169dd7406584925447bc5b25eb'
    body:
      admin: true
      cluster: "cbaf7pcd0jqk1ilrm7hg"
      endpointType: "public"
      format: "zip"
      network: true
    status_code: 200
        
- name: Delete earlier instances of kube config if any
  file:
    path: "{{ kube_config_path }}"
    state: absent

- name: ansible create directory for unzip kubeconfig
  file:
    path: "{{ kube_config_path }}"
    state: directory

- name: Unzip Kube config
  shell:
    cmd: /usr/bin/unzip "{{ zip_path }}" -d "{{ kube_config_path }}"

- name: Read config.yaml into kube_config var
  shell:
    cmd: find "{{kube_config_path}}" -name "*.yml"
  register: kube_config

- name: Display the kubeconfig file path
  debug:
    var: kube_config.stdout
